name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4.3
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Build the project
        run: yarn build

      - name: Run tests
        env:
          DATABASE_URL: mongodb://localhost:27017/testdb
          SECRET: SECRET-TEST
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          DATABASE_URL: mongodb://localhost:27017/testdb
          SECRET: SECRET-TEST
          files: ./coverage/**/lcov.info
          flags: unittests
          name: codecov-umbrella
